# Generated by Django 3.1.3 on 2020-12-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpark', '0002_auto_20201215_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpark',
            name='title',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
